### ISSUE TITLE
Detection Error

### ISSUE THREAD

**Issue by honbyk** [spectresearch/detectem#6]
* detectem version: 0.5.2
* Python version: 3.6.1
* Operating System: Win10

### Description
When i want to detect a domain. I have installed docker and pull scraping/splash.
det http://github.com
### What I Did

```
Traceback (most recent call last):
  File "c:\users\honby\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\honby\AppData\Local\Programs\Python\Python36\Scripts\det.exe\__main__.py", line 9, in <module>
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\detectem\cli.py", line 49, in main
    results = get_detection_results(url, format, metadata)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\detectem\cli.py", line 57, in get_detection_results
    plugins = load_plugins()
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\detectem\plugin.py", line 42, in load_plugins
    for module_path in get_plugin_module_paths(plugin_dir):
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\detectem\plugin.py", line 28, in get_plugin_module_paths
    relative_paths = [re.sub(plugin_dir.rstrip('/') + '/', '', fp) for fp in filepaths]
  File "c:\users\honby\appdata\local\programs\python\python36\lib\site-packages\detectem\plugin.py", line 28, in <listcomp>
    relative_paths = [re.sub(plugin_dir.rstrip('/') + '/', '', fp) for fp in filepaths]
  File "c:\users\honby\appdata\local\programs\python\python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "c:\users\honby\appdata\local\programs\python\python36\lib\sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "c:\users\honby\appdata\local\programs\python\python36\lib\sre_parse.py", line 362, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
sre_constants.error: incomplete escape \u at position 2
```

**Comment by csalazar** [comment]
Hi @honbyk, currently the project isn't supported under Windows. I expect someone could help us to debug and resolve it.
